# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/VineetKiragi/CMPE-257/blob/main/Preprocessing.ipynb
"""

import requests
import json
import pandas as pd

"""## Initial Analysis of Squad Data Format"""

#importing the dataset into the notebook
!wget 'https://raw.githubusercontent.com/rajpurkar/SQuAD-explorer/master/dataset/train-v1.1.json'
with open("train-v1.1.json") as f:
  squad = json.load(f)

squad['data'][0].keys()

"""As we can see there are two keys in the dataset, title and paragraph

Each title has many paragraph inside it, and for each paragraph there are many questions and corresponding answers.

So there are 35 rows with title and paragraph keys in this dataset

## Preprocesing
"""

import json

from google.colab import drive
drive.mount('/content/drive')

# This file has been saved in my Google Drive
with open('/content/drive/MyDrive/merged_file.json', 'rb') as f:
  val_data= json.load(f)

print('Size of the complete dataset ' + str(len(val_data['data'])))

import numpy as np
import pandas as pd

def squad_to_df(path):
    file = json.loads(open(path).read())

    json_data = pd.json_normalize(file, 'data')
    qas = pd.json_normalize(file, ['data','paragraphs','qas'])
    context = pd.json_normalize(file,['data','paragraphs'])
    
    #print(r['context'].values)

    contexts = np.repeat(context['context'].values, context.qas.str.len())
    qas['context'] = contexts

    data = qas[['id','question','context','answers']].set_index('id').reset_index()
    data['context_id'] = data['context'].factorize()[0]
    
    return data

data = squad_to_df('/content/drive/MyDrive/merged_file.json')
data.head()

"""## Get Unique Documents"""

data[['context']].drop_duplicates().reset_index(drop=True)